@extends('layouts.app')
@section('title','Dashboard')
@section('content')
<div class="dashboard-bar d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3">
    <div class="d-flex align-items-center gap-2"><span class="dashboard-mark"><i class="fa-solid fa-house" aria-hidden="true"></i></span><span class="section-label mb-0">Dashboard</span></div>
    <div class="d-flex gap-2"><a class="btn btn-sm btn-light" href="{{ route('reports.stock') }}"><i class="fa-solid fa-chart-column" aria-hidden="true"></i> View report</a><a class="btn btn-sm btn-primary" href="{{ route('stock.index') }}"><i class="fa-solid fa-plus" aria-hidden="true"></i> Record stock</a></div>
</div>
<div class="row g-2 mb-2">
    @foreach([['fa-file-invoice-dollar','Total A/R','$'.number_format($receivables,2),'Customer opening balances','blue'],['fa-boxes-stacked','Inventory value','$'.number_format($inventory,2),'Quantity x average cost','violet'],['fa-money-bill-transfer','Total A/P','$'.number_format($payables,2),'Vendor opening balances','amber'],['fa-triangle-exclamation','Reorder alerts',$alerts,'Items at or below reorder level','rose']] as $m)
        <div class="col-sm-6 col-xl-3"><div class="card metric-card position-relative"><div class="card-body"><div class="metric-label">{{ $m[1] }}</div><div class="metric-value">{{ $m[2] }}</div><div class="metric-foot">{{ $m[3] }}</div><span class="metric-symbol {{ $m[4] }}"><i class="fa-solid {{ $m[0] }}" aria-hidden="true"></i></span></div></div></div>
    @endforeach
</div>
<div class="card dashboard-panel mb-2">
    <div class="panel-heading"><h2 class="h6 mb-0"><i class="fa-solid fa-chart-column me-1" aria-hidden="true"></i>Inventory activity overview</h2><span class="text-secondary small">Current reporting period</span></div>
    <div class="dashboard-chart"><div class="dashboard-chart-empty"><div><i class="fa-solid fa-chart-line" aria-hidden="true"></i>Activity charts will populate as stock movements are posted.</div></div></div>
</div>
<div class="row g-2">
    <div class="col-xl-7"><div class="card dashboard-widget-table h-100"><div class="panel-heading"><h2 class="h6 mb-0"><i class="fa-solid fa-clock-rotate-left me-1" aria-hidden="true"></i>Recent stock activity</h2><a href="{{ route('stock.index') }}" class="panel-link">View all <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Document</th><th>Date</th><th>Movement</th><th>Item</th><th class="text-end">Quantity</th><th>Status</th></tr></thead><tbody>@forelse($recent as $row)<tr><td class="fw-semibold">{{ $row->number }}</td><td>{{ $row->movement_date->format('d M Y') }}</td><td>{{ str($row->kind)->title() }}</td><td>{{ $row->item->name }}</td><td class="text-end">{{ $row->quantity }}</td><td><x-status :value="$row->posted?'posted':'draft'" /></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">No stock movements yet.</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="col-xl-5"><div class="card dashboard-panel h-100"><div class="panel-heading"><h2 class="h6 mb-0"><i class="fa-solid fa-bolt me-1" aria-hidden="true"></i>Quick actions</h2></div><div class="card-body pt-0"><a class="quick-action" href="{{ route('items.index') }}"><span class="quick-icon"><i class="fa-solid fa-boxes-stacked" aria-hidden="true"></i></span><span><strong>Item catalog</strong><small>Products, costs, and stock levels</small></span><b><i class="fa-solid fa-arrow-right" aria-hidden="true"></i></b></a><a class="quick-action" href="{{ route('purchasing.index') }}"><span class="quick-icon"><i class="fa-solid fa-cart-shopping" aria-hidden="true"></i></span><span><strong>Purchase orders</strong><small>Plan the next supplier order</small></span><b><i class="fa-solid fa-arrow-right" aria-hidden="true"></i></b></a><a class="quick-action" href="{{ route('stock.index') }}"><span class="quick-icon"><i class="fa-solid fa-right-left" aria-hidden="true"></i></span><span><strong>Stock movement</strong><small>Receive, issue, or adjust stock</small></span><b><i class="fa-solid fa-arrow-right" aria-hidden="true"></i></b></a><a class="quick-action" href="{{ route('reports.stock') }}"><span class="quick-icon"><i class="fa-solid fa-chart-pie" aria-hidden="true"></i></span><span><strong>Stock valuation</strong><small>Review inventory value</small></span><b><i class="fa-solid fa-arrow-right" aria-hidden="true"></i></b></a></div></div></div>
</div>
@endsection
