@extends('layouts.app')
@php($plural=$kind==='vendor'?'vendors':'customers')
@section('title',ucfirst($plural))
@section('content')
<x-page-header :eyebrow="$kind==='vendor'?'Purchasing':'Sales'" :title="ucfirst($kind).' center'" :description="'Manage '.$kind.' details, balances, and activity.'"/>
<div class="card"><x-toolbar :placeholder="'Search '.$kind.' code, name, or email...'" :filters="['Active records','Balance: any']" :create-label="'Add '.ucfirst($kind)"/>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Code</th><th>Name</th><th>Contact</th><th>Phone</th><th class="text-end">{{ $kind==='customer'?'Open balance':'Opening balance' }}</th><th>Status</th><th></th></tr></thead><tbody>@forelse($records as $row)<tr><td>{{ $row->code }}</td><td class="fw-semibold"><a class="record-link" href="{{ route($plural.'.show',$row) }}">{{ $row->name }}</a></td><td>{{ $row->email ?: '-' }}</td><td>{{ $row->phone ?: '-' }}</td><td class="text-end">${{ number_format($kind==='customer'?$row->open_balance:$row->opening_balance,2) }}</td><td><x-status :value="$row->active?'active':'inactive'"/></td><td class="text-end">@if(auth()->user()->role !== 'viewer')<a class="table-action" href="{{ route($plural.'.edit',$row) }}"><i class="fa-solid fa-pen" aria-hidden="true"></i><span class="visually-hidden">Edit</span></a>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-5">No {{ $plural }} found. Add your first {{ $kind }} to begin.</td></tr>@endforelse</tbody></table></div><div class="card-footer bg-white">{{ $records->links() }}</div></div>
<div class="modal fade" id="recordModal"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="{{ route($plural.'.store') }}">@csrf<div class="modal-header"><h2 class="modal-title fs-5">Add {{ $kind }}</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><x-contact-fields :contact="new \App\Models\Contact"/></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save {{ $kind }}</button></div></form></div></div>
@endsection
