<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HealthCheckController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\PasswordResetController;
use App\Http\Controllers\PayableController;
use App\Http\Controllers\PurchaseOrderController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SalesOrderController;
use App\Http\Controllers\StockMovementController;
use Illuminate\Support\Facades\Route;

Route::get('/health', HealthCheckController::class)->name('health');

Route::get('/login', [AuthController::class, 'create'])->name('login');
Route::post('/login', [AuthController::class, 'store'])->middleware('throttle:5,1')->name('login.store');
Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
Route::get('/forgot-password', [PasswordResetController::class, 'requestForm'])->middleware('guest')->name('password.request');
Route::post('/forgot-password', [PasswordResetController::class, 'sendLink'])->middleware(['guest', 'throttle:5,1'])->name('password.email');
Route::get('/reset-password/{token}', [PasswordResetController::class, 'resetForm'])->middleware('guest')->name('password.reset');
Route::post('/reset-password', [PasswordResetController::class, 'reset'])->middleware(['guest', 'throttle:5,1'])->name('password.update');
Route::middleware(['auth', 'throttle:120,1', 'idle.timeout'])->group(function () {
    Route::redirect('/', '/dashboard');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/vendors', [ContactController::class, 'vendors'])->name('vendors.index');
    Route::post('/vendors', [ContactController::class, 'storeVendor'])->middleware(['ledger.write', 'throttle.writes'])->name('vendors.store');
    Route::get('/vendors/{contact}/edit', [ContactController::class, 'editVendor'])->name('vendors.edit');
    Route::put('/vendors/{contact}', [ContactController::class, 'updateVendor'])->middleware(['ledger.write', 'throttle.writes'])->name('vendors.update');
    Route::get('/vendors/{contact}', [ContactController::class, 'showVendor'])->name('vendors.show');
    Route::get('/customers', [ContactController::class, 'customers'])->name('customers.index');
    Route::post('/customers', [ContactController::class, 'storeCustomer'])->middleware(['ledger.write', 'throttle.writes'])->name('customers.store');
    Route::get('/customers/{contact}/edit', [ContactController::class, 'editCustomer'])->name('customers.edit');
    Route::put('/customers/{contact}', [ContactController::class, 'updateCustomer'])->middleware(['ledger.write', 'throttle.writes'])->name('customers.update');
    Route::get('/customers/{contact}', [ContactController::class, 'showCustomer'])->name('customers.show');
    Route::get('/items', [ItemController::class, 'index'])->name('items.index');
    Route::get('/items/create', [ItemController::class, 'create'])->name('items.create');
    Route::post('/items', [ItemController::class, 'store'])->middleware(['ledger.write', 'throttle.writes'])->name('items.store');
    Route::post('/items/import', [ItemController::class, 'import'])->middleware(['ledger.write', 'throttle.writes'])->name('items.import');
    Route::get('/items/{item}/edit', [ItemController::class, 'edit'])->name('items.edit');
    Route::put('/items/{item}', [ItemController::class, 'update'])->middleware(['ledger.write', 'throttle.writes'])->name('items.update');
    Route::patch('/items/{item}/archive', [ItemController::class, 'archive'])->middleware(['ledger.write', 'throttle.writes'])->name('items.archive');
    Route::get('/purchasing', [PurchaseOrderController::class, 'index'])->name('purchasing.index');
    Route::post('/purchasing', [PurchaseOrderController::class, 'store'])->middleware(['ledger.write', 'throttle.writes'])->name('purchasing.store');
    Route::get('/purchasing/{order}', [PurchaseOrderController::class, 'show'])->name('purchasing.show');
    Route::post('/purchasing/{order}/approve', [PurchaseOrderController::class, 'approve'])->middleware(['ledger.approve', 'throttle.writes'])->name('purchasing.approve');
    Route::post('/purchasing/{order}/receive', [PurchaseOrderController::class, 'receive'])->middleware(['ledger.write', 'throttle.writes'])->name('purchasing.receive');
    Route::get('/payables', [PayableController::class, 'index'])->name('payables.index');
    Route::post('/payables', [PayableController::class, 'store'])->middleware(['ledger.write', 'throttle.writes'])->name('payables.store');
    Route::post('/payables/payments', [PayableController::class, 'payment'])->middleware(['ledger.write', 'throttle.writes'])->name('payables.payment');
    Route::get('/sales', [SalesOrderController::class, 'index'])->name('sales.index');
    Route::post('/sales', [SalesOrderController::class, 'store'])->middleware(['ledger.write', 'throttle.writes'])->name('sales.store');
    Route::get('/sales/{order}', [SalesOrderController::class, 'show'])->name('sales.show');
    Route::post('/sales/{order}/approve', [SalesOrderController::class, 'approve'])->middleware(['ledger.approve', 'throttle.writes'])->name('sales.approve');
    Route::post('/sales/{order}/deliver', [SalesOrderController::class, 'deliver'])->middleware(['ledger.write', 'throttle.writes'])->name('sales.deliver');
    Route::post('/sales/{order}/invoice', [SalesOrderController::class, 'invoice'])->middleware(['ledger.write', 'throttle.writes'])->name('sales.invoice');
    Route::post('/sales/{order}/receipt', [SalesOrderController::class, 'receipt'])->middleware(['ledger.write', 'throttle.writes'])->name('sales.receipt');
    Route::get('/stock', [StockMovementController::class, 'index'])->name('stock.index');
    Route::post('/stock', [StockMovementController::class, 'store'])->middleware(['ledger.write', 'throttle.writes'])->name('stock.store');
    Route::post('/stock/{movement}/post', [StockMovementController::class, 'post'])->middleware(['ledger.write', 'throttle.writes'])->name('stock.post');
    Route::post('/stock/{movement}/reverse', [StockMovementController::class, 'reverse'])->middleware(['ledger.write', 'throttle.writes'])->name('stock.reverse');
    Route::get('/accounting', [AccountController::class, 'index'])->name('accounting.index');
    Route::post('/accounting', [AccountController::class, 'store'])->middleware(['ledger.write', 'throttle.writes'])->name('accounting.store');
    Route::get('/reports/stock-valuation', [ReportController::class, 'stock'])->name('reports.stock');
    Route::get('/reports/receivables-aging', [ReportController::class, 'receivables'])->name('reports.receivables');
    Route::get('/reports/payables-aging', [ReportController::class, 'payables'])->name('reports.payables');
});
