<?php
use App\Http\Controllers\{AccountController,AuthController,ContactController,DashboardController,ItemController,PurchaseOrderController,ReportController,StockMovementController}; use Illuminate\Support\Facades\Route;
Route::get('/login',[AuthController::class,'create'])->name('login'); Route::post('/login',[AuthController::class,'store'])->middleware('throttle:5,1')->name('login.store'); Route::post('/logout',[AuthController::class,'destroy'])->name('logout');
Route::middleware('auth')->group(function(){
 Route::redirect('/','/dashboard'); Route::get('/dashboard',DashboardController::class)->name('dashboard');
 Route::get('/vendors',[ContactController::class,'vendors'])->name('vendors.index'); Route::post('/vendors',[ContactController::class,'storeVendor'])->middleware('ledger.write')->name('vendors.store'); Route::get('/vendors/{contact}/edit',[ContactController::class,'editVendor'])->name('vendors.edit'); Route::put('/vendors/{contact}',[ContactController::class,'updateVendor'])->middleware('ledger.write')->name('vendors.update'); Route::get('/vendors/{contact}',[ContactController::class,'showVendor'])->name('vendors.show');
 Route::get('/customers',[ContactController::class,'customers'])->name('customers.index'); Route::post('/customers',[ContactController::class,'storeCustomer'])->middleware('ledger.write')->name('customers.store'); Route::get('/customers/{contact}/edit',[ContactController::class,'editCustomer'])->name('customers.edit'); Route::put('/customers/{contact}',[ContactController::class,'updateCustomer'])->middleware('ledger.write')->name('customers.update'); Route::get('/customers/{contact}',[ContactController::class,'showCustomer'])->name('customers.show');
 Route::get('/items',[ItemController::class,'index'])->name('items.index'); Route::get('/items/create',[ItemController::class,'create'])->name('items.create'); Route::post('/items',[ItemController::class,'store'])->middleware('ledger.write')->name('items.store'); Route::post('/items/import',[ItemController::class,'import'])->middleware('ledger.write')->name('items.import'); Route::get('/items/{item}/edit',[ItemController::class,'edit'])->name('items.edit'); Route::put('/items/{item}',[ItemController::class,'update'])->middleware('ledger.write')->name('items.update'); Route::patch('/items/{item}/archive',[ItemController::class,'archive'])->middleware('ledger.write')->name('items.archive');
 Route::get('/purchasing',[PurchaseOrderController::class,'index'])->name('purchasing.index'); Route::post('/purchasing',[PurchaseOrderController::class,'store'])->middleware('ledger.write')->name('purchasing.store'); Route::get('/purchasing/{order}',[PurchaseOrderController::class,'show'])->name('purchasing.show'); Route::post('/purchasing/{order}/approve',[PurchaseOrderController::class,'approve'])->middleware('ledger.approve')->name('purchasing.approve'); Route::post('/purchasing/{order}/receive',[PurchaseOrderController::class,'receive'])->middleware('ledger.write')->name('purchasing.receive');
 Route::get('/stock',[StockMovementController::class,'index'])->name('stock.index'); Route::post('/stock',[StockMovementController::class,'store'])->middleware('ledger.write')->name('stock.store'); Route::post('/stock/{movement}/post',[StockMovementController::class,'post'])->middleware('ledger.write')->name('stock.post'); Route::post('/stock/{movement}/reverse',[StockMovementController::class,'reverse'])->middleware('ledger.write')->name('stock.reverse');
 Route::get('/accounting',[AccountController::class,'index'])->name('accounting.index'); Route::post('/accounting',[AccountController::class,'store'])->middleware('ledger.write')->name('accounting.store');
 Route::get('/reports/stock-valuation',ReportController::class)->name('reports.stock');
});
