@extends('layouts.app')
@section('title',$order->number)
@section('content')
<div class="entry-page-header d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><span class="section-label">Procurement</span><h1 class="h5 mb-0 mt-1">Purchase order {{ $order->number }}</h1></div><div class="d-flex gap-2"><a class="btn btn-sm btn-light" href="{{ route('purchasing.index') }}"><i class="fa-solid fa-arrow-left" aria-hidden="true"></i> Purchase orders</a>@if($order->status === 'draft' && in_array(auth()->user()->role,['owner','admin','accountant']))<form method="post" action="{{ route('purchasing.approve',$order) }}">@csrf<button class="btn btn-sm btn-primary" onclick="return confirm('Approve this purchase order?')"><i class="fa-solid fa-check" aria-hidden="true"></i> Approve</button></form>@endif</div></div>
<div class="card mb-3"><div class="card-body p-3"><div class="row g-3"><div class="col-md-4"><div class="section-label">Vendor</div><div class="fw-semibold">{{ $order->vendor->name }}</div><div class="small text-secondary">{{ $order->vendor->code }}</div></div><div class="col-md-2"><div class="section-label">Order date</div><div>{{ $order->order_date->format('d M Y') }}</div></div><div class="col-md-2"><div class="section-label">Expected</div><div>{{ $order->expected_date?->format('d M Y') ?? '-' }}</div></div><div class="col-md-2"><div class="section-label">Status</div><x-status :value="$order->status"/></div><div class="col-md-2"><div class="section-label">Total</div><div class="fw-semibold">${{ number_format($order->total,2) }}</div></div></div></div></div>
<div class="card mb-3"><div class="panel-heading"><h2 class="h6 mb-0">Order lines</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>Product</th><th class="text-end">Ordered</th><th class="text-end">Received</th><th class="text-end">Remaining</th><th class="text-end">Unit cost</th><th class="text-end">Line total</th></tr></thead><tbody>@foreach($order->lines as $line)<tr><td>{{ $line->item->sku }} · {{ $line->item->name }}</td><td class="text-end">{{ $line->quantity }}</td><td class="text-end">{{ $line->received_quantity }}</td><td class="text-end">{{ number_format((float)$line->quantity-(float)$line->received_quantity,2) }}</td><td class="text-end">${{ number_format($line->unit_cost,2) }}</td><td class="text-end">${{ number_format($line->line_total,2) }}</td></tr>@endforeach</tbody></table></div></div>
@if(in_array($order->status,['approved','partially_received']) && auth()->user()->role !== 'viewer')
<div class="card mb-3"><div class="panel-heading"><h2 class="h6 mb-0">Receive goods</h2></div><form method="post" action="{{ route('purchasing.receive',$order) }}">@csrf<div class="card-body p-3"><div class="row g-3 mb-3"><div class="col-md-4"><label class="form-label">Receipt number</label><input class="form-control" name="number" value="GR-{{ date('Ymd-His') }}" required></div><div class="col-md-4"><label class="form-label">Receipt date</label><input type="date" class="form-control" max="{{ date('Y-m-d') }}" name="receipt_date" value="{{ date('Y-m-d') }}" required></div><div class="col-md-4"><label class="form-label">Warehouse</label><select class="form-select" name="warehouse_id" required>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->code }} · {{ $warehouse->name }}</option>@endforeach</select></div></div><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Product</th><th class="text-end">Remaining</th><th style="width:180px">Receive now</th></tr></thead><tbody>@foreach($order->lines as $line)@php($remaining=(float)$line->quantity-(float)$line->received_quantity)@if($remaining>0)<tr><td>{{ $line->item->sku }} · {{ $line->item->name }}<input type="hidden" name="lines[{{ $line->id }}][purchase_order_line_id]" value="{{ $line->id }}"></td><td class="text-end">{{ number_format($remaining,2) }}</td><td><input type="number" min="0" max="{{ $remaining }}" step="0.01" class="form-control form-control-sm" name="lines[{{ $line->id }}][quantity]" value="{{ $remaining }}"></td></tr>@endif@endforeach</tbody></table></div><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div><div class="card-footer bg-white text-end"><button class="btn btn-primary" @disabled($warehouses->isEmpty())><i class="fa-solid fa-box-open" aria-hidden="true"></i> Post goods receipt</button></div></form></div>
@endif
@if($order->goodsReceipts->isNotEmpty())<div class="card"><div class="panel-heading"><h2 class="h6 mb-0">Goods receipt history</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>Receipt</th><th>Date</th><th>Warehouse</th><th class="text-end">Lines</th></tr></thead><tbody>@foreach($order->goodsReceipts as $receipt)<tr><td class="fw-semibold">{{ $receipt->number }}</td><td>{{ $receipt->receipt_date->format('d M Y') }}</td><td>{{ $receipt->warehouse->name }}</td><td class="text-end">{{ $receipt->lines->count() }}</td></tr>@endforeach</tbody></table></div></div>@endif
@endsection
