@extends('layouts.app')
@section('title','Payables')
@section('content')
<div class="module-header d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><div class="section-label mb-1">Purchasing</div><h1 class="h4 mb-1 fw-semibold">Vendor bills and payments</h1><p class="text-secondary mb-0 small">Record what is owed to suppliers and settle it against individual bills.</p></div><a class="btn btn-sm btn-light" href="{{ route('reports.payables') }}">A/P aging</a></div>
@if(auth()->user()->role !== 'viewer')
<div class="card mb-3"><div class="panel-heading"><h2 class="h6 mb-0">Record vendor bill</h2></div><form method="post" action="{{ route('payables.store') }}">@csrf<div class="card-body p-3"><div class="row g-2"><div class="col-md-3"><label class="form-label">Number</label><input class="form-control" name="number" value="BILL-{{ date('Ymd-His') }}" required></div><div class="col-md-3"><label class="form-label">Vendor</label><select class="form-select" name="vendor_id" required><option value="">Choose vendor</option>@foreach($vendors as $vendor)<option value="{{ $vendor->id }}">{{ $vendor->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Bill date</label><input type="date" class="form-control" name="bill_date" value="{{ date('Y-m-d') }}" required></div><div class="col-md-2"><label class="form-label">Due date</label><input type="date" class="form-control" name="due_date"></div><div class="col-md-2"><label class="form-label">Description</label><input class="form-control" name="lines[0][description]" required></div><div class="col-md-3"><label class="form-label">Quantity</label><input type="number" min="0.01" step="0.01" class="form-control" name="lines[0][quantity]" value="1" required></div><div class="col-md-3"><label class="form-label">Unit cost</label><input type="number" min="0" step="0.01" class="form-control" name="lines[0][unit_cost]" required></div><div class="col-md-6"><label class="form-label">Notes</label><input class="form-control" name="notes"></div></div></div><div class="card-footer bg-white text-end"><button class="btn btn-primary">Record bill</button></div></form></div>
@endif
<div class="card"><div class="panel-heading"><h2 class="h6 mb-0">Vendor bills</h2></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Bill</th><th>Vendor</th><th>Bill date</th><th>Due</th><th>Status</th><th class="text-end">Total</th><th class="text-end">Open</th><th></th></tr></thead><tbody>
@forelse($bills as $bill)
<tr><td class="fw-semibold">{{ $bill->number }}</td><td>{{ $bill->vendor->name }}</td><td>{{ $bill->bill_date->format('d M Y') }}</td><td>{{ $bill->due_date?->format('d M Y') ?? '-' }}</td><td><x-status :value="$bill->status"/></td><td class="text-end">${{ number_format($bill->total,2) }}</td><td class="text-end">${{ number_format($bill->open_balance,2) }}</td><td class="text-end">@if($bill->status === 'open' && auth()->user()->role !== 'viewer')<button class="btn btn-sm btn-outline-primary" data-bs-toggle="collapse" data-bs-target="#pay-{{ $bill->id }}">Pay</button>@endif</td></tr>
@if($bill->status === 'open' && auth()->user()->role !== 'viewer')
<tr class="collapse" id="pay-{{ $bill->id }}"><td colspan="8"><form method="post" action="{{ route('payables.payment') }}" class="row g-2 align-items-end">@csrf<input type="hidden" name="vendor_id" value="{{ $bill->vendor_id }}"><input type="hidden" name="allocations[0][vendor_bill_id]" value="{{ $bill->id }}"><div class="col-md-3"><label class="form-label">Payment number</label><input class="form-control form-control-sm" name="number" value="PAY-{{ date('Ymd-His') }}" required></div><div class="col-md-2"><label class="form-label">Date</label><input type="date" class="form-control form-control-sm" name="payment_date" value="{{ date('Y-m-d') }}" required></div><div class="col-md-2"><label class="form-label">Amount</label><input type="number" class="form-control form-control-sm" min="0.01" max="{{ $bill->open_balance }}" step="0.01" name="amount" value="{{ $bill->open_balance }}" required></div><div class="col-md-2"><label class="form-label">Allocate</label><input type="number" class="form-control form-control-sm" min="0.01" max="{{ $bill->open_balance }}" step="0.01" name="allocations[0][amount]" value="{{ $bill->open_balance }}" required></div><div class="col-md-2"><label class="form-label">Reference</label><input class="form-control form-control-sm" name="reference"></div><div class="col-md-1"><button class="btn btn-sm btn-primary">Save</button></div></form></td></tr>
@endif
@empty
<tr><td colspan="8" class="text-center text-secondary py-5">No vendor bills recorded.</td></tr>
@endforelse
</tbody></table></div>@if($bills->hasPages())<div class="card-footer bg-white">{{ $bills->links() }}</div>@endif</div>
@endsection
