<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('companies',fn(Blueprint $t)=>[$t->uuid('id')->primary(),$t->string('name',160),$t->char('currency',3)->default('USD'),$t->string('timezone',80)->default('Asia/Phnom_Penh'),$t->timestamps()]);
  Schema::create('users',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->string('name',120);$t->string('email',190)->unique();$t->timestamp('email_verified_at')->nullable();$t->string('password');$t->enum('role',['owner','admin','accountant','operator','viewer'])->default('operator');$t->boolean('active')->default(true);$t->rememberToken();$t->timestamps();});
  Schema::create('contacts',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->enum('kind',['customer','vendor']);$t->string('code',32);$t->string('name',180);$t->string('email',190)->nullable();$t->string('phone',50)->nullable();$t->string('tax_id',80)->nullable();$t->text('address')->nullable();$t->decimal('opening_balance',18,2)->default(0);$t->boolean('active')->default(true);$t->timestamps();$t->unique(['company_id','code']);$t->index(['company_id','kind']);});
  Schema::create('warehouses',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->string('code',24);$t->string('name',120);$t->boolean('active')->default(true);$t->unique(['company_id','code']);});
  Schema::create('item_groups',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->string('code',24);$t->string('name',120);$t->timestamps();$t->unique(['company_id','code']);});
  Schema::create('items',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->foreignUuid('group_id')->nullable()->constrained('item_groups')->nullOnDelete();$t->string('sku',64);$t->string('name',180);$t->string('barcode',80)->nullable();$t->string('unit',32)->default('Each');$t->decimal('cost',18,2)->default(0);$t->decimal('sale_price',18,2)->default(0);$t->decimal('reorder_level',18,2)->default(0);$t->decimal('quantity',18,2)->default(0);$t->boolean('active')->default(true);$t->timestamps();$t->unique(['company_id','sku']);});
  Schema::create('purchase_orders',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->foreignUuid('vendor_id')->constrained('contacts');$t->string('number',40);$t->date('order_date');$t->date('expected_date')->nullable();$t->enum('status',['draft','approved','partially_received','received','cancelled'])->default('draft');$t->decimal('total',18,2)->default(0);$t->text('notes')->nullable();$t->timestamps();$t->unique(['company_id','number']);});
  Schema::create('stock_movements',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->foreignUuid('warehouse_id')->constrained();$t->foreignUuid('item_id')->constrained();$t->string('number',40);$t->date('movement_date');$t->enum('kind',['receipt','issue','adjustment','transfer','assembly']);$t->string('reference',100)->nullable();$t->decimal('quantity',18,2);$t->boolean('posted')->default(false);$t->text('notes')->nullable();$t->timestamps();$t->unique(['company_id','number']);});
  Schema::create('accounts',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->string('code',32);$t->string('name',160);$t->enum('category',['asset','liability','equity','revenue','expense']);$t->decimal('balance',18,2)->default(0);$t->boolean('active')->default(true);$t->unique(['company_id','code']);});
  Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->foreignUuid('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action',80);$t->string('entity_type',80);$t->uuid('entity_id')->nullable();$t->json('metadata')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['company_id','created_at']);});
 }
 public function down():void { foreach(['audit_logs','accounts','stock_movements','purchase_orders','items','item_groups','warehouses','contacts','users','companies'] as $table) Schema::dropIfExists($table); }
};
