@extends('layouts.app')
@section('title','Sales orders')
@section('content')
<div class="module-header d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><div class="section-label mb-1">Sales</div><h1 class="h4 mb-1 fw-semibold">Sales orders</h1><p class="text-secondary mb-0 small">Create customer orders, post deliveries, and invoice fulfilled quantities.</p></div>@if(auth()->user()->role !== 'viewer')<button class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#new-sales-order"><i class="fa-solid fa-plus" aria-hidden="true"></i> New sales order</button>@endif</div>

@if(auth()->user()->role !== 'viewer')
<div class="collapse mb-3" id="new-sales-order"><div class="card"><div class="panel-heading"><h2 class="h6 mb-0">New sales order</h2></div><form method="post" action="{{ route('sales.store') }}">@csrf<div class="card-body p-3"><div class="row g-3 mb-3"><div class="col-md-3"><label class="form-label">Order number</label><input class="form-control" name="number" value="SO-{{ date('Ymd-His') }}" required></div><div class="col-md-4"><label class="form-label">Customer</label><select class="form-select" name="customer_id" required><option value="">Choose customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->code }} · {{ $customer->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Order date</label><input class="form-control" type="date" name="order_date" value="{{ date('Y-m-d') }}" max="{{ date('Y-m-d') }}" required></div><div class="col-md-3"><label class="form-label">Expected delivery</label><input class="form-control" type="date" name="expected_date"></div></div><input type="hidden" name="status" value="draft"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Product</th><th style="width:140px">Quantity</th><th style="width:170px">Unit price</th><th class="text-end">Line total</th><th></th></tr></thead><tbody id="so-lines"><tr class="so-line"><td><select class="form-select form-select-sm so-item" required><option value="">Choose product</option>@foreach($items as $item)<option value="{{ $item->id }}" data-price="{{ $item->sale_price }}">{{ $item->sku }} · {{ $item->name }}</option>@endforeach</select></td><td><input class="form-control form-control-sm so-quantity" type="number" min="0.01" step="0.01" value="1" required></td><td><div class="input-group input-group-sm"><span class="input-group-text">$</span><input class="form-control so-price" type="number" min="0" step="0.01" required></div></td><td class="text-end so-line-total">$0.00</td><td class="text-center"><button type="button" class="btn btn-sm btn-link text-danger remove-so-line" title="Remove line"><i class="fa-solid fa-trash-can" aria-hidden="true"></i></button></td></tr></tbody><tfoot><tr><th colspan="3" class="text-end">Order total</th><th class="text-end" id="so-total">$0.00</th><th></th></tr></tfoot></table></div><button class="btn btn-sm btn-outline-primary" type="button" id="add-so-line"><i class="fa-solid fa-plus" aria-hidden="true"></i> Add product</button><div class="mt-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div></div><div class="card-footer bg-white text-end"><button class="btn btn-primary">Create draft</button></div></form></div></div>
<template id="so-line-template"><tr class="so-line"><td><select class="form-select form-select-sm so-item" required><option value="">Choose product</option>@foreach($items as $item)<option value="{{ $item->id }}" data-price="{{ $item->sale_price }}">{{ $item->sku }} · {{ $item->name }}</option>@endforeach</select></td><td><input class="form-control form-control-sm so-quantity" type="number" min="0.01" step="0.01" value="1" required></td><td><div class="input-group input-group-sm"><span class="input-group-text">$</span><input class="form-control so-price" type="number" min="0" step="0.01" required></div></td><td class="text-end so-line-total">$0.00</td><td class="text-center"><button type="button" class="btn btn-sm btn-link text-danger remove-so-line" title="Remove line"><i class="fa-solid fa-trash-can" aria-hidden="true"></i></button></td></tr></template>
@endif

<div class="card"><div class="panel-heading d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Orders</h2><form class="d-flex gap-2" method="get"><input class="form-control form-control-sm" name="q" value="{{ request('q') }}" placeholder="Order or customer"><button class="btn btn-sm btn-light">Search</button></form></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Status</th><th class="text-end">Total</th></tr></thead><tbody>@forelse($orders as $order)<tr><td><a class="fw-semibold" href="{{ route('sales.show',$order) }}">{{ $order->number }}</a></td><td>{{ $order->customer->name }}</td><td>{{ $order->order_date->format('d M Y') }}</td><td><x-status :value="$order->status"/></td><td class="text-end">${{ number_format($order->total,2) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">No sales orders yet.</td></tr>@endforelse</tbody></table></div>@if($orders->hasPages())<div class="card-body">{{ $orders->links() }}</div>@endif</div>
@endsection
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const body=document.getElementById('so-lines'),template=document.getElementById('so-line-template'),total=document.getElementById('so-total'),money=n=>'$'+(Number(n)||0).toFixed(2),renumber=()=>body?.querySelectorAll('.so-line').forEach((row,index)=>{row.querySelector('.so-item').name=`lines[${index}][item_id]`;row.querySelector('.so-quantity').name=`lines[${index}][quantity]`;row.querySelector('.so-price').name=`lines[${index}][unit_price]`;}),calculate=()=>{let sum=0;body?.querySelectorAll('.so-line').forEach(row=>{const value=(parseFloat(row.querySelector('.so-quantity').value)||0)*(parseFloat(row.querySelector('.so-price').value)||0);row.querySelector('.so-line-total').textContent=money(value);sum+=value;});if(total)total.textContent=money(sum);};document.getElementById('add-so-line')?.addEventListener('click',()=>{body.append(template.content.cloneNode(true));renumber();calculate();});body?.addEventListener('input',calculate);body?.addEventListener('change',event=>{if(event.target.matches('.so-item')){const price=event.target.selectedOptions[0]?.dataset.price;if(price!==undefined)event.target.closest('.so-line').querySelector('.so-price').value=price;}calculate();});body?.addEventListener('click',event=>{if(event.target.closest('.remove-so-line')&&body.querySelectorAll('.so-line').length>1){event.target.closest('.so-line').remove();renumber();calculate();}});renumber();calculate();});</script>
@endpush
